In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC  # Corrected import
from sklearn.ensemble import RandomForestClassifier  # Corrected import
import numpy as np
from sklearn.datasets import load_digits


In [4]:
digits = load_digits()

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data , digits.target, test_size=0.3)

In [11]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test,y_test)

C:\python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [12]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test,y_test)

0.9888888888888889

In [19]:
rt = RandomForestClassifier(n_estimators=40)
rt.fit(x_train,y_train)
rt.score(x_test,y_test)

0.9666666666666667

In [21]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)

kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [61]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)

# Iterate through the train and test indices
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8,9]):
    print(train_index, test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [62]:
def get_score(model, x_train , x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test,y_test)

In [29]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [63]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9549248747913188

In [64]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9181969949916527

In [65]:
from sklearn.model_selection import StratifiedGroupKFold
folds = StratifiedGroupKFold(n_splits=3)


In [66]:
score_l = []
score_svm = []
score_rf = []

for train_index,test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test= digits.data[train_index], digits.data[test_index], \
    digits.target[train_index],digits.target[test_index]
    
    score_svm.append( get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))
    score_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    
   
    
    


C:\python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_resu

In [82]:
score_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [78]:
score_rf

[0.9332220367278798, 0.9565943238731218, 0.9181969949916527]

In [79]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [80]:
from sklearn.model_selection import cross_val_score

In [81]:
cross_val_score(LogisticRegression(),digits.data, digits.target)

C:\python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_resu

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [58]:
cross_val_score(SVC(),digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [59]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target)

array([0.92222222, 0.87222222, 0.95543175, 0.9637883 , 0.91086351])